apiVersion: v1
kind: Service
metadata:
  name: googlefinance-stocks-info-service
  namespace: googlefinance-stocks-info
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    k8s-app: googlefinance-stocks-info
